CtJobeetBundle_job:
    resource: "@CtJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job

CtJobeetBundle_homepage:
    path:     /
    defaults: { _controller: CtJobeetBundle:Job:index }
