CtJobeetBundle_job:
    resource: "@CtJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job

CtJobeetBundle_homepage:
    path:     /
    defaults: { _controller: CtJobeetBundle:Job:index }

CtJobeetBundle_category:
    path:   /category/{slug}
    defaults: { _controller: CtJobeetBundle:Category:show }