ct_job:
    path:     /
    defaults: { _controller: "CtJobeetBundle:Job:index" }
    methods:  GET

ct_job_show:
    path:     /{company}/{location}/{id}/{position}
    defaults: { _controller: "CtJobeetBundle:Job:show" }
    methods:  GET
    requirements:
        id:  \d+

ct_job_new:
    path:     /new
    defaults: { _controller: "CtJobeetBundle:Job:new" }
    methods:  [GET, POST]

ct_job_edit:
    path:     /{id}/edit
    defaults: { _controller: "CtJobeetBundle:Job:edit" }
    methods:  [GET, POST]

ct_job_delete:
    path:     /{id}/delete
    defaults: { _controller: "CtJobeetBundle:Job:delete" }
    methods:  DELETE
